# Description
#   Random vegetable
#
# Configuration:
#   
#
# Commands:
#   hubot vegetable - responds with random vegetable
#
# Author:
#   Ravikiran Janardhana <ravikiran.j.127@gmail.com>

vegetables = [
    "Ahipa",
    "Amaranth",
    "American groundnut",
    "Aonori",
    "Arame",
    "Arracacha",
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Avocado",
    "Azuki bean",
    "Bamboo shoot",
    "Beet",
    "Beetroot",
    "Bell pepper",
    "Bitter melon",
    "Black-eyed pea",
    "Bok choy",
    "Borage",
    "Broadleaf arrowhead",
    "Broccoli",
    "Broccoli",
    "Broccolini",
    "Brussels sprouts",
    "Burdock",
    "Cabbage",
    "Camas",
    "Canna",
    "Caper",
    "Cardoon",
    "Carola",
    "Carrot",
    "Cassava",
    "Catsear",
    "Cauliflower",
    "Celeriac",
    "Celery",
    "Celery",
    "Celtuce",
    "Chaya",
    "Chayote",
    "Chickpea",
    "Chickweed",
    "Chicory",
    "Chinese artichoke",
    "Chinese mallow",
    "Chives",
    "Chrysanthemum",
    "Collard greens",
    "Common bean",
    "Common purslane",
    "Corn salad",
    "Courgette flowers",
    "Cress",
    "Cucumber",
    "Dabberlocks",
    "Daikon",
    "Dandelion",
    "Daylily",
    "Dill",
    "Dolichos bean",
    "Drumstick",
    "Dulse",
    "Earthnut pea",
    "Eggplant",
    "Elephant foot yam",
    "Elephant garlic",
    "Endive",
    "Ensete",
    "Fat hen",
    "Fava bean",
    "Fiddlehead",
    "Florence fennel",
    "Fluted pumpkin",
    "Galangal",
    "Garbanzo",
    "Garden rocket",
    "Garlic",
    "Garlic chives",
    "Gau soon",
    "Gim",
    "Ginger",
    "Golden samphire",
    "Good King Henry",
    "Grape",
    "Greater plantain",
    "Green bean",
    "Guar",
    "Hamburg parsley",
    "Hijiki",
    "Horse gram",
    "Horseradish",
    "Indian pea",
    "Ivy gourd",
    "Jerusalem artichoke",
    "Jícama",
    "Kai-lan",
    "Kale",
    "Kohlrabi",
    "Komatsuna",
    "Kombu",
    "Kuka",
    "Kurrat",
    "Lagos bologi",
    "Lamb's lettuce",
    "Lamb's quarters",
    "Land cress",
    "Laver",
    "Leek",
    "Lemongrass",
    "Lentil",
    "Lettuce",
    "Lima bean",
    "Lizard's tail",
    "Lotus root",
    "Luffa",
    "Malabar spinach",
    "Marrow",
    "Mashua",
    "Melokhia",
    "Miner's lettuce",
    "Mizuna greens",
    "Moth bean",
    "Mozuku",
    "Mung bean",
    "Mustard",
    "Napa cabbage",
    "New Zealand Spinach",
    "Nopal",
    "Nori",
    "Ogonori",
    "Okra",
    "Olive fruit",
    "Onion",
    "Orache",
    "Pak choy",
    "Paracress",
    "Parsnip",
    "Pea",
    "Pea",
    "Peanut",
    "Pearl onion",
    "Pigeon pea",
    "Pignut",
    "Poke",
    "Potato",
    "Potato onion",
    "Prairie turnip",
    "Prussian asparagus",
    "Pumpkin",
    "Radicchio",
    "Radish",
    "Rapini",
    "Ricebean",
    "Runner bean",
    "Rutabaga",
    "Salsify",
    "Samphire",
    "Scorzonera",
    "Sculpit",
    "Sea beet",
    "Sea grape",
    "Sea kale",
    "Sea lettuce",
    "Shallot",
    "Shepherd's purse",
    "Sierra Leone bologi",
    "Skirret",
    "Snap pea",
    "Snow pea",
    "Soko",
    "Sorrel",
    "Sour cabbage",
    "Soybean",
    "Spinach",
    "Scallion",
    "Squash",
    "Squash blossoms",
    "Stridolo",
    "Summer purslane",
    "Swede",
    "Sweet pepper",
    "Sweet potato",
    "Swiss chard",
    "Taro",
    "Tarwi",
    "Tatsoi",
    "Tepary bean",
    "Ti",
    "Tigernut",
    "Tinda",
    "Tomatillo",
    "Tomato",
    "Tree onion",
    "Turmeric",
    "Turnip",
    "Turnip",
    "Ulluco",
    "Urad bean",
    "Vanilla",
    "Velvet bean",
    "Wakame",
    "Wasabi",
    "Water caltrop",
    "Water chestnut",
    "Water spinach",
    "Watercress",
    "Welsh onion",
    "West Indian gherkin",
    "Wheatgrass",
    "Wild leek",
    "Winged bean",
    "Winter melon",
    "Yacón",
    "Yam",
    "Yao choy",
    "Yardlong bean",
    "Yarrow",
    "Zucchini"
]

module.exports = (robot) ->
    robot.respond /vegetable/, (msg) ->
        randomVegetable = vegetables[Math.floor(Math.random()*vegetables.length)]
        encodedVegetable = encodeURIComponent(randomVegetable)
        msg.send "Vegetable = #{randomVegetable}, Wikipedia = https://en.wikipedia.org/wiki/#{encodedVegetable}"
